### ISSUE TITLE
Levenshtein realisation counts substitution as 2 edits instead of 1

### ISSUE THREAD

**Issue by 4ilin** [rapidfuzz/Levenshtein#57]
The distance in your documentation is defined as the minimum number of insertions, deletions, and substitutions.

When I calculate the ratio between the following strings, it gives me the following:

1. "abcde" vs "abcd"	is (9-1)/9 = 0.888888889 (correct)
2. "abcde 1" vs "abcde 2" = (14-2)/14=0.857142857 (incorrect)

I expect a higher similarity in the second case, but the library considers substitution as two edits (deletion and insertion) instead of one.

**Comment by maxbachmann** [comment]
The documentation was not super clear on this. `ratio` calculates a similarity based on the indel distance which only allows insertions and deletions (behaves the same as levenshtein with substitution weight 2).

`distance` calculates the normal Levenshtein distance, so I understand why this is surprising. This is done for legacy reason, since this has always been the behavior in this library. I would recommend you to use `rapidfuzz` instead which is used here internally as well:
```
>> from rapidfuzz.distance import Levenshtein
>> Levenshtein.normalized_similarity("abcde", "abcd")
0.8
>>> Levenshtein.normalized_similarity("abcde", "abcde 2")
0.7142857142857143
```
while indel gives you:
```
>>> from rapidfuzz.distance import Indel
>>> Indel.normalized_similarity("abcde", "abcd")
0.8888888888888888
>>> Indel.normalized_similarity("abcde", "abcde 2")
0.8333333333333334
```


Note that uniform levenshtein is normalized using `max(len1, len2)`, while the indel distance is normalized using `len1 + len2`. The reason for this is that it uses the maximum possible score for normalization. For Indel that is removing all characters and then inserting all of the other string, while for Levenshtein it's replacing the common part and removing/inserting the length difference.

**Comment by 4ilin** [comment]
Thank you for your prompt reply, Max. That's very clear. As deletion counts for 2, it all adds up.
