### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by Maxl94** [rapidfuzz/Levenshtein#61]
Hey,
I use this package to calculate the string distances for a paper. Do you have some paper in relation with this package to cite? Otherwise I am going to use the Github website.

Thanks for your work!
Max

**Comment by maxbachmann** [comment]
Unless you are using one of the following functions:
- median,
- median_improve,
- quickmedian,
- seqratio,
- setmedian,
-  setratio,

I would just directly use rapidfuzz, since for all others it is only a thin wrapper around rapidfuzz anyways: https://github.com/rapidfuzz/Levenshtein/blob/main/src/Levenshtein/__init__.py

Rapidfuzz can be cited via zenodo: https://github.com/rapidfuzz/RapidFuzz/blob/main/CITATION.bib. It automatically generates a doi for each release. I generally prefer people citing rapidfuzz since it has a pretty unique name. From time to time I search open access papers on google scholar for it (https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=rapidfuzz&btnG=) to see which cool projects make use of my library :)
